"""Export Decision Tree / Random Forest sang một file header C++ thuần (không cần thư viện).

Cách dùng:
    python -m spike_ai.export_cpp --model models/<run>/move__decision_tree.joblib --out exports/

Sinh ra exports/spike_ai_<target>_<model>.h gồm:
    - kFeatureNames / kNumFeatures      : thứ tự feature BẮT BUỘC khi gọi model
    - kClassNames                        : tên class theo đúng thứ tự output
    - PredictProba(const float* x, float* out)
    - PredictIndex(const float* x)       : index class có xác suất cao nhất
    - RunGoldenTest()                    : so sánh với kết quả Python (phải trả về true)

Cây được lưu dạng bảng (node -> left/right/feature/threshold) và duyệt bằng vòng lặp,
giống hệt cách sklearn dự đoán: đi sang trái nếu x[feature] <= threshold.
"""

import argparse
import re
from pathlib import Path

import joblib
import numpy as np

from .models import EXPORTABLE
from .paths import resolve

GOLDEN_TOLERANCE = 1e-5


def _trees(model):
    """Danh sách cây sklearn trong model (1 cây với Decision Tree, n cây với Random Forest)."""
    return list(model.estimators_) if hasattr(model, "estimators_") else [model]


def tree_tables(tree) -> dict:
    """Rút bảng node từ một cây sklearn; xác suất lá đã được chuẩn hoá."""
    t = tree.tree_
    value = t.value[:, 0, :].astype(float)
    total = value.sum(axis=1, keepdims=True)
    proba = np.divide(value, total, out=np.zeros_like(value), where=total > 0)
    return {
        "left": t.children_left.tolist(),
        "right": t.children_right.tolist(),
        "feature": t.feature.tolist(),
        "threshold": t.threshold.tolist(),
        "proba": proba.tolist(),
    }


def predict_proba_from_tables(tables: list[dict], x) -> np.ndarray:
    """Tái hiện đúng thuật toán C++ bằng Python - dùng để tự kiểm tra exporter."""
    out = np.zeros(len(tables[0]["proba"][0]))
    for tb in tables:
        node = 0
        while tb["left"][node] != -1:
            node = tb["left"][node] if float(np.float32(x[tb["feature"][node]])) <= tb["threshold"][node] \
                else tb["right"][node]
        out += tb["proba"][node]
    return out / len(tables)


def _fmt(v: float) -> str:
    return repr(float(v))


def render_header(bundle: dict, tables: list[dict]) -> str:
    target, model_name = bundle["target"], bundle["model_name"]
    ns = re.sub(r"\W", "_", f"{target}_{model_name}")
    features, classes = bundle["features"], bundle["classes"]
    n_f, n_c = len(features), len(classes)

    lines = [
        "// AUTO-GENERATED by spike_ai.export_cpp - KHÔNG sửa tay, hãy export lại.",
        f"// schema={bundle['schema']}  agent={bundle['agent']}  target={target}  model={model_name}",
        "// Agent bên phải (opponent): toạ độ x phải lật qua lưới trước khi tính feature,",
        "// và kết quả move phải đổi dấu khi đưa về game. Xem docs/integration.md.",
        "#pragma once",
        "#include <cmath>",
        "",
        f"namespace spike_ai::{ns}",
        "{",
        f"constexpr int kNumFeatures = {n_f};",
        f"constexpr int kNumClasses  = {n_c};",
        f"constexpr int kNumTrees    = {len(tables)};",
        "",
        "constexpr const char* kFeatureNames[kNumFeatures] = {",
        *[f'    "{f}",' for f in features],
        "};",
        "",
        "constexpr const char* kClassNames[kNumClasses] = {",
        *[f'    "{c}",' for c in classes],
        "};",
        "",
        "struct Node",
        "{",
        "    int left;        // -1 = lá",
        "    int right;",
        "    int feature;",
        "    double threshold;  // đi sang trái nếu x[feature] <= threshold",
        "};",
        "",
    ]

    for i, tb in enumerate(tables):
        lines.append(f"constexpr Node kTree{i}[] = {{")
        for l, r, f, th in zip(tb["left"], tb["right"], tb["feature"], tb["threshold"]):
            lines.append(f"    {{{l}, {r}, {f if l != -1 else 0}, {_fmt(th) if l != -1 else '0.0'}}},")
        lines.append("};")
        lines.append(f"constexpr float kTree{i}Proba[][kNumClasses] = {{")
        for p in tb["proba"]:
            lines.append("    {" + ", ".join(f"{v:.9g}f" for v in p) + "},")
        lines.append("};")
        lines.append("")

    lines += [
        "struct Tree",
        "{",
        "    const Node* nodes;",
        "    const float (*proba)[kNumClasses];",
        "};",
        "",
        "constexpr Tree kTrees[kNumTrees] = {",
        *[f"    {{kTree{i}, kTree{i}Proba}}," for i in range(len(tables))],
        "};",
        "",
        "inline void PredictProba(const float* x, float* out)",
        "{",
        "    for (int c = 0; c < kNumClasses; ++c)",
        "        out[c] = 0.0f;",
        "    for (int t = 0; t < kNumTrees; ++t)",
        "    {",
        "        const Node* nodes = kTrees[t].nodes;",
        "        int node = 0;",
        "        while (nodes[node].left != -1)",
        "            node = (static_cast<double>(x[nodes[node].feature]) <= nodes[node].threshold) ? nodes[node].left",
        "                                                                                        : nodes[node].right;",
        "        for (int c = 0; c < kNumClasses; ++c)",
        "            out[c] += kTrees[t].proba[node][c];",
        "    }",
        "    for (int c = 0; c < kNumClasses; ++c)",
        "        out[c] /= static_cast<float>(kNumTrees);",
        "}",
        "",
        "inline int PredictIndex(const float* x)",
        "{",
        "    float proba[kNumClasses];",
        "    PredictProba(x, proba);",
        "    int best = 0;",
        "    for (int c = 1; c < kNumClasses; ++c)",
        "        if (proba[c] > proba[best])",
        "            best = c;",
        "    return best;",
        "}",
        "",
        "// ---- Golden test: vector lấy từ tập test, kết quả do Python (sklearn) tính ----",
        f"constexpr int kNumGolden = {len(bundle['golden_X'])};",
        "constexpr float kGoldenX[kNumGolden][kNumFeatures] = {",
        *["    {" + ", ".join(f"{v:.9g}f" for v in row) + "}," for row in bundle["golden_X"]],
        "};",
        "constexpr float kGoldenProba[kNumGolden][kNumClasses] = {",
        *["    {" + ", ".join(f"{v:.9g}f" for v in row) + "}," for row in bundle["golden_proba"]],
        "};",
        "",
        "inline bool RunGoldenTest()",
        "{",
        "    for (int i = 0; i < kNumGolden; ++i)",
        "    {",
        "        float proba[kNumClasses];",
        "        PredictProba(kGoldenX[i], proba);",
        "        for (int c = 0; c < kNumClasses; ++c)",
        f"            if (std::fabs(proba[c] - kGoldenProba[i][c]) > {GOLDEN_TOLERANCE}f)",
        "                return false;",
        "    }",
        "    return true;",
        "}",
        f"}}  // namespace spike_ai::{ns}",
        "",
    ]
    return "\n".join(lines)


def export(model_path: str | Path, out_dir: str | Path) -> Path:
    bundle = joblib.load(resolve(model_path))
    if bundle["model_name"] not in EXPORTABLE:
        raise ValueError(f"Model '{bundle['model_name']}' chưa hỗ trợ export C++. Hỗ trợ: {sorted(EXPORTABLE)}")

    tables = [tree_tables(t) for t in _trees(bundle["model"])]

    # Tự kiểm tra: thuật toán duyệt bảng phải cho cùng xác suất với sklearn
    for x, expected in zip(bundle["golden_X"], bundle["golden_proba"]):
        got = predict_proba_from_tables(tables, x)
        if not np.allclose(got, expected, atol=GOLDEN_TOLERANCE):
            raise AssertionError(f"Bảng cây khác sklearn: {got} vs {expected}")

    out_dir = resolve(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"spike_ai_{bundle['target']}_{bundle['model_name']}.h"
    out_path.write_text(render_header(bundle, tables), encoding="utf-8")

    n_nodes = sum(len(t["left"]) for t in tables)
    print(f"Đã export {out_path} ({len(tables)} cây, {n_nodes} node, "
          f"{out_path.stat().st_size / 1024:.0f} KB). Golden test Python: OK")
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model", required=True, help="file .joblib do spike_ai.train tạo ra")
    parser.add_argument("--out", default="exports", help="thư mục đầu ra")
    args = parser.parse_args()
    export(args.model, args.out)


if __name__ == "__main__":
    main()
